# Generated by Django 5.2.8 on 2025-11-20 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradeprint_backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('short_description', models.TextField(blank=True)),
                ('full_description', models.TextField(blank=True)),
                ('tags', models.CharField(blank=True, max_length=300)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('trending', models.CharField(choices=[('top', 'Top'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('short_description', models.TextField(blank=True)),
                ('full_description', models.TextField(blank=True)),
                ('tags', models.CharField(blank=True, max_length=300)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('trending', models.CharField(choices=[('top', 'Top'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='tradeprint_backend.category')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
