# Generated by Django 5.2.8 on 2025-11-20 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradeprint_backend', '0002_category_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('short_description', models.TextField(blank=True)),
                ('full_description', models.TextField(blank=True)),
                ('tags', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], max_length=10)),
                ('trending', models.CharField(choices=[('top', 'Top'), ('medium', 'Medium'), ('low', 'Low')], max_length=10)),
                ('parent_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tradeprint_backend.category')),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tradeprint_backend.subcategory')),
            ],
        ),
    ]
