# Generated by Django 5.2.8 on 2025-11-30 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradeprint_backend', '0004_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='image_1',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='product',
            name='allow_different_designs',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='banding_options',
            field=models.JSONField(blank=True, default=list, help_text='Banding options with price modifiers'),
        ),
        migrations.AddField(
            model_name='product',
            name='base_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Base price for the product', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='delivery_options',
            field=models.JSONField(blank=True, default=list, help_text='Delivery speed options with prices'),
        ),
        migrations.AddField(
            model_name='product',
            name='double_sided_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Additional price for double sided', max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_4',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_5',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_6',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AddField(
            model_name='product',
            name='lamination_options',
            field=models.JSONField(blank=True, default=list, help_text='Lamination options with price modifiers'),
        ),
        migrations.AddField(
            model_name='product',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='products/main/'),
        ),
        migrations.AddField(
            model_name='product',
            name='material_options',
            field=models.JSONField(blank=True, default=list, help_text='Material options with price modifiers'),
        ),
        migrations.AddField(
            model_name='product',
            name='max_different_designs',
            field=models.IntegerField(default=1, help_text='Maximum number of different designs allowed'),
        ),
        migrations.AddField(
            model_name='product',
            name='min_order_quantity',
            field=models.IntegerField(default=1, help_text='Minimum order quantity'),
        ),
        migrations.AddField(
            model_name='product',
            name='quantity_tiers',
            field=models.JSONField(blank=True, default=list, help_text='Quantity-based pricing tiers'),
        ),
        migrations.AddField(
            model_name='product',
            name='sides_printed',
            field=models.CharField(choices=[('single', 'Single Sided'), ('double', 'Double Sided'), ('both', 'Both Available')], default='both', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='size_options',
            field=models.JSONField(blank=True, default=list, help_text='Size options with price modifiers'),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_quantity',
            field=models.IntegerField(default=0, help_text='Available stock quantity'),
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.CharField(blank=True, help_text='Comma separated tags', max_length=500),
        ),
    ]
