# Generated by Django 4.2.7 on 2025-12-07 18:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tradeprint_backend', '0007_order_orderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='address',
            new_name='shipping_address',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='city',
            new_name='shipping_city',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='country',
            new_name='shipping_country',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='email',
            new_name='shipping_email',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='first_name',
            new_name='shipping_first_name',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='last_name',
            new_name='shipping_last_name',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='phone',
            new_name='shipping_phone',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='postcode',
            new_name='shipping_postcode',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='state',
            new_name='shipping_state',
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('postcode', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='tradeprint_backend.customer'),
        ),
    ]
