# Generated by Django 4.2.7 on 2025-12-13 16:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tradeprint_backend', '0009_order_barcode_image_order_is_sent_to_printer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='artwork_file',
            field=models.FileField(blank=True, null=True, upload_to='artwork/cart/'),
        ),
        migrations.AddField(
            model_name='order',
            name='invoice_pdf',
            field=models.FileField(blank=True, null=True, upload_to='invoices/'),
        ),
        migrations.AddField(
            model_name='order',
            name='is_artwork_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='artwork_file',
            field=models.FileField(blank=True, null=True, upload_to='artwork/orders/'),
        ),
        migrations.CreateModel(
            name='PrintShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=150)),
                ('location', models.CharField(max_length=255)),
                ('contact_phone', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='print_shop_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='assigned_shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_orders', to='tradeprint_backend.printshop'),
        ),
    ]
