# Generated by Django 4.2.7 on 2025-12-19 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradeprint_backend', '0010_cartitem_artwork_file_order_invoice_pdf_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='printshop',
            options={'ordering': ['-created_at'], 'verbose_name': 'Print Shop', 'verbose_name_plural': 'Print Shops'},
        ),
        migrations.AddField(
            model_name='printshop',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='printshop',
            name='business_registration_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='printshop',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='printshop',
            name='daily_capacity',
            field=models.IntegerField(default=50, help_text='Maximum orders per day'),
        ),
        migrations.AddField(
            model_name='printshop',
            name='monthly_capacity',
            field=models.IntegerField(default=1000, help_text='Maximum orders per month'),
        ),
        migrations.AddField(
            model_name='printshop',
            name='postcode',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='printshop',
            name='tax_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='printshop',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
